MODE_NORMAL = 'Normal'
MODE_HARD = 'Hard'
MODES = {'1': MODE_NORMAL,
         '2': MODE_HARD}

MIN_ATTACK_VALUE = 1
MAX_ATTACK_VALUE = 3

START = '1'
SCORES = '2'
EXIT = '3'

FIGHT = 'fight'
KILL = 'kill'

SCORES_ADDING_TYPES = [FIGHT,KILL]

ENEMY_LIVES = 5
ENEMY_LIVES_FOR_MODE_HARD = 6
PLAYER_LIVES = 5
PLAYER_LIVES_FOR_MODE_HARD = 3
POINTS_FOR_FIGHT = 1
POINTS_FOR_FIGHT_FOR_MODE_HARD = 2
POINTS_FOR_KILLING = 5
POINTS_FOR_KILLING_FOR_MODE_HARD = 10
MAX_RECORDS_NUMBER = 10

SCORES_TO_ADD = {
    MODE_NORMAL : {
        FIGHT : POINTS_FOR_FIGHT,
        KILL : POINTS_FOR_KILLING
    },
    MODE_HARD : {
        FIGHT : POINTS_FOR_FIGHT_FOR_MODE_HARD,
        KILL : POINTS_FOR_KILLING_FOR_MODE_HARD
    },
}
SCORE_FILE = 'scores.txt'

PAPER = 'Paper'
STONE = 'Stone'
SCISSORS = 'Scissors'

WIN = 1
DRAW = 0
LOSE = -1

ALLOWED_ATTACKS = {
    '1': PAPER,
    '2': STONE,
    '3': SCISSORS
}

ATTACK_PAIRS_OUTCOME = {
    (PAPER, PAPER): DRAW,
    (PAPER, STONE): WIN,
    (PAPER, SCISSORS): LOSE,
    (STONE, PAPER): LOSE,
    (STONE, STONE): DRAW,
    (STONE, SCISSORS): WIN,
    (SCISSORS, PAPER): WIN,
    (SCISSORS, STONE): LOSE,
    (SCISSORS, SCISSORS): DRAW
}